version: '3.3'
services:
  api:
    build: ./api
    container_name: api_backend
    restart: always
    ports:
      - '4000:4000'
    networks:
      - calamutka
    volumes:
      - ./api:/app
      - ./app/node_modules
  client:
    build: ./client
    container_name: client_frontend
    restart: always
    ports:
      - '3000:3000'
    networks:
      - calamutka
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
  client-admin:
    build: ./client-admin
    container_name: client_frontend_admin
    restart: always
    ports:
      - '3001:3001'
    networks:
      - calamutka
    volumes:
      - ./client-admin:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
  nginx-proxy:
    image: nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - calamutka
    restart: always
networks:
  calamutka:
    driver: bridge
