version: '3'

services:
  api:
    build: ./api
    container_name: api_backend
    restart: always
    networks:
      - calamutka
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
    environment:
      - VIRTUAL_HOST=api.calamutka.com
      - LETSENCRYPT_HOST=api.calamutka.com
      - LETSENCRYPT_EMAIL=Drakyla60@gmail.com
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
  client:
    build: ./client
    container_name: client_frontend
    restart: always
    networks:
      - calamutka
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    stdin_open: true
    tty: true
    environment:
      - VIRTUAL_HOST=calamutka.com
      - LETSENCRYPT_HOST=calamutka.com
      - LETSENCRYPT_EMAIL=Drakyla60@gmail.com
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0

  client-admin:
    build: ./client-admin
    container_name: client_frontend_admin
    restart: always
    networks:
      - calamutka
    volumes:
      - ./client-admin:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
    environment:
      - VIRTUAL_HOST=admin.calamutka.com
      - LETSENCRYPT_HOST=admin.calamutka.com
      - LETSENCRYPT_EMAIL=Drakyla60@gmail.com

  mysql:
    image: mysql:latest
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: calamutka
      MYSQL_DATABASE: calamutka
      MYSQL_USER: calamutka
      MYSQL_PASSWORD: calamutka
    ports:
      - '3306:3306'
    volumes:
      - ./var/data/mysql:/var/lib/mysql
    networks:
      - calamutka

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf  # Сюди треба додати конфіг nginx
      - ./nginx/ssl:/etc/letsencrypt
    networks:
      - calamutka
    depends_on:
      - api
      - client
      - client-admin
      - mysql

networks:
  calamutka:
    driver: bridge
