version: '3'

services:
  api:
    build: ./api
    container_name: api_backend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.calamutka.com`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.services.api.loadbalancer.server.port=4000"
      - "traefik.http.middlewares.cors.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=\
                GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=\
                Origin,Content-Type,Accept,Authorization"
    networks:
      - calamutka
    volumes:
      - ./api:/app
      - ./app/node_modules

  client:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    build: ./client
    container_name: client_frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`calamutka.com`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls=true"
      - "traefik.http.services.client.loadbalancer.server.port=3000"
    networks:
      - calamutka
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

  client-admin:
    build: ./client-admin
    container_name: client_frontend_admin
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client-admin.rule=Host(`admin.calamutka.com`)"
      - "traefik.http.routers.client-admin.entrypoints=websecure"
      - "traefik.http.routers.client-admin.tls=true"
      - "traefik.http.services.client-admin.loadbalancer.server.port=3001"
    networks:
      - calamutka
    volumes:
      - ./client-admin:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

  mysql:
    image: mysql:latest
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: calamutka
      MYSQL_DATABASE: calamutka
      MYSQL_USER: calamutka
      MYSQL_PASSWORD: calamutka
    ports:
      - '3300:3306'
    volumes:
      - ./var/data/mysql:/var/lib/mysql
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"  # Дозволяє підключатися з будь-якого домену
      - "traefik.tcp.routers.mysql.tls=true"  # Включає TLS для захисту підключень
      - "traefik.tcp.routers.mysql.tls.certresolver=myresolver"  # Вказує, який CertResolver використовувати

    networks:
      - calamutka

  traefik:
    image: "traefik:v2.5"
    container_name: traefik
    command:
      - "--api.insecure=true"
#      - "--configFile=/traefik.yml"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--certificatesresolvers.default.acme.httpchallenge=true"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.default.acme.email=Drakyla60@gmail.com"  # Замініть на свій електронний адрес
      - "--certificatesresolvers.default.acme.storage=/acme.json"
#      - "traefik.http.middlewares.debug.headers.customRequestHeaders=X-Debug-Mode: true"
      - "--log.level=DEBUG"
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
    restart: always
    networks:
      - calamutka
    depends_on:
      - api
      - client
      - client-admin
      - mysql

networks:
  calamutka:
    driver: bridge
